
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzerr;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TkGuionCurseado = 15;
  public static final int TkPARENTESISCierra = 9;
  public static final int TkGuionBajo = 17;
  public static final int TkOr = 11;
  public static final int TkDOSPUNTOS = 4;
  public static final int TkPARENTESISAbre = 8;
  public static final int TkENTERO = 18;
  public static final int TkLLAVEC = 7;
  public static final int TkLLAVEA = 6;
  public static final int TkDECIMAL = 19;
  public static final int TKMulti = 24;
  public static final int EOF = 0;
  public static final int TkCADENA = 20;
  public static final int TkICaracter = 23;
  public static final int TkCOMA = 5;
  public static final int TkCerraduraKleen = 27;
  public static final int error = 1;
  public static final int TkPUNTOYCOMA = 3;
  public static final int TkErChar = 21;
  public static final int TkInterrogacion = 13;
  public static final int TkICaracterEspecial = 26;
  public static final int TkConcatenacion = 14;
  public static final int TkGuionNormal = 16;
  public static final int TkIdentificador = 22;
  public static final int TkMas = 12;
  public static final int TkDelimitador = 10;
  public static final int TkCONJ_R = 2;
  public static final int TkUni = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TkCONJ_R",
  "TkPUNTOYCOMA",
  "TkDOSPUNTOS",
  "TkCOMA",
  "TkLLAVEA",
  "TkLLAVEC",
  "TkPARENTESISAbre",
  "TkPARENTESISCierra",
  "TkDelimitador",
  "TkOr",
  "TkMas",
  "TkInterrogacion",
  "TkConcatenacion",
  "TkGuionCurseado",
  "TkGuionNormal",
  "TkGuionBajo",
  "TkENTERO",
  "TkDECIMAL",
  "TkCADENA",
  "TkErChar",
  "TkIdentificador",
  "TkICaracter",
  "TKMulti",
  "TkUni",
  "TkICaracterEspecial",
  "TkCerraduraKleen"
  };
}

